function generarUtagData(){let utag_data={domain:'lda',platform:'/escritorio',app:'/estaticos',product:setProducto(),seccion:setSeccion(),page_name:setPageName()}
return utag_data;}
function generarUtagDataHome(){let utag_data={domain:'lda',platform:'/escritorio',app:'/estaticos',product:"homeLDA",seccion:setSeccion(),page_name:setPageName()}
return utag_data;}
function generarUtagDataFidelizaciones(){let utag_data={domain:'lda',platform:'/escritorio',app:'/Clientes',product:setProducto(),seccion:'/Fidelizacion',page_name:setPageNameFidelizaciones()}
return utag_data;}
function generarUtagDataLandings(){let utag_data={domain:setDominioLanding(),platform:'/escritorio',app:'/landing',product:setProductoLanding(),seccion:setSeccionLanding(),page_name:setPageNameLanding()}
return utag_data;}
function incluirTealium(){var scr=document.createElement("script");var url='';var dom='';var ruta='//tags.tiqcdn.com/utag/lineadirectaaseguradorasa/';if((window.location!==window.parent.location)&&(window.parent.location.href.split("/clientes")[0].includes("penelope"))){url=window.parent.location.href;dom='pg5';}else{url=document.URL;dom=utag_data.domain;}
ruta+=dom+'/';if(url.includes("localhost")||url.includes("desarrollo.lda")){ruta+='dev';}else if(url.includes("training.lda")){ruta+='qa';}else{ruta+='prod';}
ruta+='/utag.js';scr.setAttribute("src",ruta);scr.setAttribute("type","text/javascript");document.body.appendChild(scr);}
function setDominioLanding(){if(window.location.hostname.includes('aprecioseguros')||getLiferayPageURL().includes('/web/moto-aprecioseguros')){return'aps';}else{return'lda';}}
function setProducto(){var pageURL=getLiferayPageURL();var primerNivel=pageURL.split('/')[1];var producto='';if(primerNivel.includes("autonomos-empresas")||primerNivel.includes("assegurances-flotes-empresa")){producto='/empresas';if(pageURL.includes("/multirriesgo-negocios")){producto='/multirriesgo';}}else if(primerNivel.includes("coche")||pageURL.includes("car-insurance")||pageURL.includes("assegurances-cotxe")){producto='/coche';}else if(primerNivel.includes("moto")||pageURL.includes("motorbike-insurance")||pageURL.includes("assegurances-moto")){producto='/moto';}else if(primerNivel.includes("hogar")||pageURL.includes("home-insurance")||pageURL.includes("assegurances-llar")){producto='/hogar';}else if(primerNivel.includes("salud")||pageURL.includes("health-insurance")||pageURL.includes("assegurances-salut")){producto='/salud';}else if(primerNivel.includes("movilidad")||pageURL.includes("personal-mobility-insurance")||pageURL.includes("asseguran�a-mobilitat-personal")){producto='/movilidad';}else if(primerNivel.includes("ocupacion")||pageURL.includes("occupation-insurance")||pageURL.includes("asseguran�a-ocupacio")){producto='/ocupacion';}else if(primerNivel.includes("mascotas")||pageURL.includes("pet-insurance")||pageURL.includes("assegurances-de-mascota")){producto='/mascotas';}else{producto='/'+primerNivel.split('.html')[0];}
return producto;}
function setProductoLanding(){var pageURL=getLiferayPageURL();var primerNivel=pageURL.split('/')[1];var producto='';if(primerNivel.includes("multirriesgo")){producto='/multirriesgo';}else if(primerNivel.includes("multi")||primerNivel.includes("coche-hogar")||primerNivel.includes("coche-moto")||primerNivel.includes("youtube-generica")){producto='/multi';}else if(primerNivel.includes("coche")||primerNivel.includes("car")||primerNivel.includes("dg-libre-eleccion-taller")){producto='/coches';}else if(primerNivel.includes("moto")||primerNivel.includes("motorbike")||primerNivel.includes("quad")||primerNivel.includes("ciclomotor")||primerNivel.includes("scooter")){producto='/moto';}else if(primerNivel.includes("salud")||primerNivel.includes("health")){producto='/salud';}else if(primerNivel.includes("empresas")||primerNivel.includes("autonomos")||primerNivel.includes("vehiculos-profesionales")){producto='/empresas';}else if(primerNivel.includes("hogar")||primerNivel.includes("home")){producto='/hogar';}else if(primerNivel.includes("movilidad")||primerNivel.includes("mobility")){producto='/movilidad';}else if(primerNivel.includes("ocupacion")||primerNivel.includes("occupation")){producto='/ocupacion';}else if(primerNivel.includes("llamalo-x")||primerNivel.includes("lx")){producto='/llamalox';}else if(primerNivel.includes("linea-directa")){producto='/linea-directa';}else{producto='/'+primerNivel.split('.html')[0];}
return producto;}
function setSeccion(){var pageURL=getLiferayPageURL();var segundoNivel=pageURL.split('/')[2]!==undefined?pageURL.split('/')[2]:'';if(segundoNivel!==''){segundoNivel='/'+segundoNivel.split('.html')[0];}
return segundoNivel;}
function setSeccionLanding(){var metaTag=document.querySelector('meta[property="landing_seccion"]');return metaTag?metaTag.getAttribute("content"):"";}
function setPageName(){var pageURL=getLiferayPageURL();var tercerNivel=pageURL.split('/')[3]!==undefined?pageURL.split('/')[3]:'';if(tercerNivel!==''){tercerNivel='/'+tercerNivel.split('.html')[0];}
return tercerNivel;}
function setPageNameFidelizaciones(){var pageURL=getLiferayPageURL();if(pageURL.includes("/w/promo")){return'/Fidelizacion /Mis ventajas /Promociones';}else if(pageURL.includes("/w/colaborador")){return'/Fidelizacion /Mis ventajas /Colaboradores';}else if(pageURL.includes("/ventajas")){return'/Fidelizacion /Mis ventajas';}else if(pageURL.includes("/mi-ahorro")){return'/Fidelizacion /Mi ahorro';}else if(pageURL.includes("/ahorro-historico")){return'/Fidelizacion /Mi ahorro /Informacion historico';}else if(pageURL.includes("/cambio-poliza")){return'/Fidelizacion /Mi ahorro /Informacion poliza';}else{return'/Fidelizacion /Programa ventajas';}}
function setPageNameLanding(){var metaTag=document.querySelector('meta[property="landing_page_name"]');return metaTag?metaTag.getAttribute("content"):"";}
function getLiferayPageURL(){var nivelExtra="/w/";var pageURL=Liferay.currentURL;if(pageURL.includes("/blog/")||pageURL.includes("/ayuda/")||pageURL.includes("/english-expats/facilities/")){return pageURL.replace(nivelExtra,"/");}else{return pageURL;}}
function sendEventAnalitica(category,action,label,action_google){console.log("Enviado a analitica: ('"+category+"', '"+action+"', '"+label+"', '"+action_google.toLowerCase()+"')");try{if(typeof utag_data!="undefined"){ga('send','event',category,action,label,action_google.toLowerCase(),null);}}catch(error){}}
function analiticaGetPageName(){var pageName='';try{pageName=window.utag_data.page_virtual_name;}catch(error){pageName='';}
return pageName;}
function sendEventDesdeFragmento(categoria,label,action){if(label!==''&&action!==''){var silo=setProducto().substring(1);silo=silo.charAt(0).toUpperCase()+silo.slice(1);if(window.isLanding){if(getLiferayPageURL().includes("/calcular-seguro")){sendEventAnalitica('landing-seo',silo,label,action);}else{sendEventAnalitica('Landing',silo,label,action);}}else{sendEventAnalitica(categoria,silo,label,action);}}}
function sendEventDesdeFragmentoHome(categoria,silo,label,action){if(silo!==''&&label!==''&&action!==''){if(window.isLanding){if(getLiferayPageURL().includes("/calcular-seguro")){sendEventAnalitica('landing-seo',silo,label,action);}else{sendEventAnalitica('Landing',silo,label,action);}}else{sendEventAnalitica(categoria,silo,label,action);}}}
$(document).ready(function(){if(window.location.pathname.includes("/web/porserdelineadirecta")){window.utag_data=generarUtagDataFidelizaciones();}else if(window.isLanding){if(getLiferayPageURL().includes("/calcular-seguro")){window.utag_data=generarUtagData();}else{window.utag_data=generarUtagDataLandings();}}else if(window.location.pathname==="/"){window.utag_data=generarUtagDataHome();}else{window.utag_data=generarUtagData();}
incluirTealium();});